export type AppScreen =
  | 'login'
  | 'home'
  | 'pet-profile'
  | 'add-pet'
  | 'edit-pet'
  | 'health-check'
  | 'analysis-progress'
  | 'results'
  | 'history'
  | 'onboarding-intro'
  | 'onboarding-add-pet'
  | 'onboarding-health-prompt'
  | 'onboarding-health-check'
  | 'onboarding-results';
