import {
  dewormDose,
  runScheduleTestCase,
  type ScheduleTestCaseDef,
  vaccineDose,
} from './coreCareScheduleCaseHelpers.ts';

export const EXTENDED_SCHEDULE_TEST_CASES: ScheduleTestCaseDef[] = [
  {
    id: 'CAT-06',
    title: 'Mèo chọn FeLV loại FVRCP',
    group: 'Mèo — lịch mới',
    fn: 'calculateCoreCareSchedule',
    desc: 'Sen chỉ theo dõi FeLV, không chọn FVRCP 3-in-1',
    birth: '2026-01-01',
    today: '2026-01-01',
    vaccine: 'cat_felv',
    history: 'Không có',
    path: 'filterInitialScheduleBySelection (cat)',
    checks: ['Có FeLV và tẩy giun', 'Không có FVRCP', 'Dại vẫn được giữ'],
    input: { species: 'cat', birth: '2026-01-01', today: '2026-01-01', vaccine: 'cat_felv' },
    expect: {
      has: [
        { family: 'catFelv', dose: 1, due: '2026-02-26' },
        { family: 'catRabies', dose: 1, due: '2026-04-02' },
      ],
      lacks: [{ family: 'catFvrcp', dose: 1 }],
      sorted: true,
    },
  },
  {
    id: 'CAT-07',
    title: 'Mèo chọn 4-in-1 có mũi FVRCP thứ 3',
    group: 'Mèo — lịch mới',
    fn: 'calculateCoreCareSchedule',
    desc: 'Chọn Felocell 4-in-1 cho mèo con mới sinh',
    birth: '2026-01-01',
    today: '2026-01-01',
    vaccine: 'cat_4in1',
    history: 'Không có',
    path: 'buildCatKittenIntegratedSchedule + filter',
    checks: ['Có FVRCP mũi 3', 'Không có FeLV'],
    input: { species: 'cat', birth: '2026-01-01', today: '2026-01-01', vaccine: 'cat_4in1' },
    expect: {
      has: [{ family: 'catFvrcp', dose: 3, due: '2026-04-23' }],
      lacks: [{ family: 'catFelv', dose: 1 }],
    },
  },
  {
    id: 'CAT-08',
    title: 'Mèo đúng 8 tuần tuổi hôm nay',
    group: 'Mèo — lịch mới',
    fn: 'calculateCoreCareSchedule',
    desc: 'Bé 8 tuần, chưa tiêm gì, bắt đầu catch-up tẩy giun',
    birth: '2026-05-17',
    today: '2026-07-12',
    vaccine: 'cat_3in1_fvrcp',
    history: 'Không có',
    path: 'catch-up kitten',
    checks: ['Tẩy giun #1 due hôm nay', 'FVRCP #1 sau tẩy #3 + 7 ngày'],
    input: { species: 'cat', birth: '2026-05-17', today: '2026-07-12', vaccine: 'cat_3in1_fvrcp' },
    expect: {
      has: [
        { family: 'catDeworming', dose: 1, due: '2026-07-12', catchUp: true },
        { family: 'catFvrcp', dose: 1, due: '2026-08-16' },
      ],
    },
  },
  {
    id: 'CAT-09',
    title: 'Mèo đúng 26 tuần vẫn đi nhánh mèo con',
    group: 'Mèo — biên tuổi',
    fn: 'calculateCoreCareSchedule',
    desc: '182 ngày tuổi (=26 tuần) vẫn dùng lịch mèo con, chưa adult catch-up',
    birth: '2025-07-15',
    today: '2026-01-13',
    vaccine: 'cat_3in1_fvrcp',
    history: 'Không có',
    path: 'buildCatKittenIntegratedSchedule',
    checks: ['Vẫn có chuỗi tẩy giun mèo con', 'Chưa chuyển adultCatCatchUp'],
    input: { species: 'cat', birth: '2025-07-15', today: '2026-01-13', vaccine: 'cat_3in1_fvrcp' },
    expect: {
      count: 9,
      has: [{ family: 'catFvrcp', dose: 1, due: '2026-02-17' }],
    },
  },
  {
    id: 'CAT-10',
    title: 'Mèo 27 tuần không lịch sử',
    group: 'Mèo — người lớn',
    fn: 'calculateCoreCareSchedule',
    desc: 'Mèo trưởng thành adopt mới, chọn FVRCP',
    birth: '2025-06-01',
    today: '2026-01-01',
    vaccine: 'cat_3in1_fvrcp',
    history: 'Không có',
    path: 'adultCatCatchUp',
    checks: ['FVRCP #1 due hôm nay', 'FVRCP #2 +28 ngày'],
    input: { species: 'cat', birth: '2025-06-01', today: '2026-01-01', vaccine: 'cat_3in1_fvrcp' },
    expect: {
      count: 4,
      dueDates: ['2026-01-01', '2026-01-01', '2026-01-01', '2026-01-29'],
    },
  },
  {
    id: 'CAT-11',
    title: 'Lịch mèo con được sắp xếp theo ngày',
    group: 'Mèo — lịch mới',
    fn: 'calculateCoreCareSchedule',
    desc: 'Mọi mũi trả về phải tăng dần theo dueDate',
    birth: '2026-01-01',
    today: '2026-01-01',
    vaccine: 'cat_3in1_fvrcp',
    history: 'Không có',
    path: 'finalizeScheduleRecommendations',
    checks: ['dueDate không giảm dần'],
    input: { species: 'cat', birth: '2026-01-01', today: '2026-01-01', vaccine: 'cat_3in1_fvrcp' },
    expect: { sorted: true, minCount: 10 },
  },
  {
    id: 'CAT-12',
    title: 'Mèo 12 tuần chưa tiêm gì',
    group: 'Mèo — catch-up',
    fn: 'calculateCoreCareSchedule',
    desc: 'Bé 12 tuần đến phòng khám lần đầu',
    birth: '2026-04-15',
    today: '2026-07-08',
    vaccine: 'cat_3in1_fvrcp',
    history: 'Không có',
    path: 'catch-up kitten',
    checks: ['Tẩy giun #1 hôm nay', 'FVRCP #1 sau chuỗi tẩy ban đầu'],
    input: { species: 'cat', birth: '2026-04-15', today: '2026-07-08', vaccine: 'cat_3in1_fvrcp' },
    expect: {
      has: [
        { family: 'catDeworming', dose: 1, due: '2026-07-08', catchUp: true },
        { family: 'catFvrcp', dose: 1, due: '2026-08-12' },
      ],
    },
  },
  {
    id: 'CAT-13',
    title: 'Mèo 20 tuần trễ toàn bộ lịch',
    group: 'Mèo — catch-up muộn',
    fn: 'calculateCoreCareSchedule',
    desc: 'Mèo hoang/adopt 20 tuần chưa tiêm',
    birth: '2026-02-20',
    today: '2026-07-08',
    vaccine: 'cat_3in1_fvrcp',
    history: 'Không có',
    path: 'staggerInitialCatchUpSchedule',
    checks: ['Stagger tẩy giun và FVRCP', 'Dại sau FVRCP #2'],
    input: { species: 'cat', birth: '2026-02-20', today: '2026-07-08', vaccine: 'cat_3in1_fvrcp' },
    expect: {
      has: [
        { family: 'catDeworming', dose: 1, due: '2026-07-08' },
        { family: 'catFvrcp', dose: 1, due: '2026-08-12' },
        { family: 'catRabies', dose: 1, due: '2026-09-16' },
      ],
      sorted: true,
    },
  },
  {
    id: 'CAT-14',
    title: 'Mèo con sinh mùa hè',
    group: 'Mèo — lịch mới',
    fn: 'calculateCoreCareSchedule',
    desc: 'Sinh 01/05, hôm nay 01/07 (~8 tuần)',
    birth: '2026-05-01',
    today: '2026-07-01',
    vaccine: 'cat_3in1_fvrcp',
    history: 'Không có',
    path: 'buildCatKittenIntegratedSchedule',
    checks: ['Tẩy giun #1 3 tuần tuổi đã qua → catch-up hôm nay'],
    input: { species: 'cat', birth: '2026-05-01', today: '2026-07-01', vaccine: 'cat_3in1_fvrcp' },
    expect: {
      has: [{ family: 'catDeworming', dose: 1, due: '2026-07-01', catchUp: true }],
    },
  },
  {
    id: 'CAT-15',
    title: 'Mèo không chọn vaccine vẫn có FeLV',
    group: 'Mèo — lịch mới',
    fn: 'calculateCoreCareSchedule',
    desc: 'Lịch đầy đủ khi Sen chưa chọn loại vaccine',
    birth: '2026-03-01',
    today: '2026-03-01',
    vaccine: '—',
    history: 'Không có',
    path: 'calculateCatSchedule full',
    checks: ['Có FeLV', 'Có FVRCP', 'Có dại'],
    input: { species: 'cat', birth: '2026-03-01', today: '2026-03-01' },
    expect: {
      has: [
        { family: 'catFelv', dose: 1 },
        { family: 'catFvrcp', dose: 1 },
        { family: 'catRabies', dose: 1 },
      ],
    },
  },
  {
    id: 'CAT-H04',
    title: 'Mèo lớn tiêm FVRCP hôm qua',
    group: 'Mèo — có lịch sử',
    fn: 'calculateCoreCareScheduleFromHistory',
    desc: 'Tiêm 10/07, hôm nay 11/07 — preview 3 mũi',
    birth: '2025-01-01',
    today: '2026-07-11',
    vaccine: 'cat_3in1_fvrcp',
    history: 'FVRCP: 2026-07-10',
    path: 'adult_catch_up + adjust vaccines',
    checks: ['Ẩn FVRCP #1', 'Dại hôm nay', 'Tẩy giun +7 ngày', 'FVRCP #2 +4 tuần'],
    input: {
      species: 'cat',
      birth: '2025-01-01',
      today: '2026-07-11',
      vaccine: 'cat_3in1_fvrcp',
      vaccines: [vaccineDose('cat_3in1_fvrcp', '2026-07-10')],
    },
    expect: {
      count: 3,
      dueDates: ['2026-07-11', '2026-07-17', '2026-08-07'],
      lacks: [{ family: 'catFvrcp', dose: 1 }],
    },
  },
  {
    id: 'CAT-H05',
    title: 'Mèo lớn tiêm FVRCP hôm nay chưa tẩy giun',
    group: 'Mèo — có lịch sử',
    fn: 'calculateCoreCareScheduleFromHistory',
    desc: 'Edge case tiêm vaccine trước tẩy giun',
    birth: '2025-01-01',
    today: '2026-07-11',
    vaccine: 'cat_3in1_fvrcp',
    history: 'FVRCP: 2026-07-11',
    path: 'adjustCatDewormingForRecentVaccination',
    checks: ['Tẩy giun defer +7 ngày', 'Không tẩy cùng ngày tiêm'],
    input: {
      species: 'cat',
      birth: '2025-01-01',
      today: '2026-07-11',
      vaccine: 'cat_3in1_fvrcp',
      vaccines: [vaccineDose('cat_3in1_fvrcp', '2026-07-11')],
    },
    expect: {
      has: [
        { family: 'catDeworming', dose: 1, due: '2026-07-18' },
        { family: 'catFvrcp', dose: 2, due: '2026-08-08' },
      ],
      lacks: [{ family: 'catFvrcp', dose: 1 }],
    },
  },
  {
    id: 'CAT-H06',
    title: 'Mèo lớn tiêm trùng mũi FVRCP',
    group: 'Mèo — có lịch sử',
    fn: 'calculateCoreCareScheduleFromHistory',
    desc: 'Lỗi hydrate trùng lịch sử không được tính 2 mũi',
    birth: '2025-01-01',
    today: '2026-07-11',
    vaccine: 'cat_3in1_fvrcp',
    history: 'FVRCP x2 cùng ngày (duplicate)',
    path: 'dedupeAdministeredVaccineDoses',
    checks: ['Vẫn còn FVRCP #2', 'Đủ 3 mũi preview'],
    input: {
      species: 'cat',
      birth: '2025-01-01',
      today: '2026-07-11',
      vaccine: 'cat_3in1_fvrcp',
      vaccines: [
        vaccineDose('cat_3in1_fvrcp', '2026-07-11'),
        vaccineDose('cat_3in1_fvrcp', '2026-07-11'),
      ],
    },
    expect: { count: 3, has: [{ family: 'catFvrcp', dose: 2, due: '2026-08-08' }] },
  },
  {
    id: 'CAT-H07',
    title: 'Mèo lớn đã tiêm đủ 2 mũi FVRCP',
    group: 'Mèo — có lịch sử',
    fn: 'calculateCoreCareScheduleFromHistory',
    desc: 'Chỉ còn dại và tẩy giun catch-up',
    birth: '2025-01-01',
    today: '2026-08-15',
    vaccine: 'cat_3in1_fvrcp',
    history: 'FVRCP: 11/07, 08/08',
    path: 'adult_catch_up completed primary',
    checks: ['Không còn FVRCP', 'Dại due hôm nay'],
    input: {
      species: 'cat',
      birth: '2025-01-01',
      today: '2026-08-15',
      vaccine: 'cat_3in1_fvrcp',
      vaccines: [vaccineDose('cat_3in1_fvrcp', '2026-07-11'), vaccineDose('cat_3in1_fvrcp', '2026-08-08')],
    },
    expect: {
      count: 2,
      has: [{ family: 'catRabies', dose: 1, due: '2026-08-15' }],
      lacks: [{ family: 'catFvrcp', dose: 2 }],
    },
  },
  {
    id: 'CAT-H08',
    title: 'Mèo con đã tiêm dại, chưa FVRCP',
    group: 'Mèo — có lịch sử',
    fn: 'calculateCoreCareScheduleFromHistory',
    desc: 'Sen tiêm dại sớm theo yêu cầu địa phương',
    birth: '2026-02-01',
    today: '2026-05-01',
    vaccine: 'cat_3in1_fvrcp',
    history: 'Rabies: 2026-04-20',
    path: 'cat_kitten_history',
    checks: ['Ẩn dại đã tiêm', 'Vẫn có chuỗi FVRCP'],
    input: {
      species: 'cat',
      birth: '2026-02-01',
      today: '2026-05-01',
      vaccine: 'cat_3in1_fvrcp',
      vaccines: [vaccineDose('cat_rabies', '2026-04-20')],
    },
    expect: {
      lacks: [{ family: 'catRabies', dose: 1 }],
      has: [{ family: 'catFvrcp', dose: 1 }],
    },
  },
  {
    id: 'CAT-H09',
    title: 'Mèo con đã tẩy giun 2 lần',
    group: 'Mèo — có lịch sử',
    fn: 'calculateCoreCareScheduleFromHistory',
    desc: 'Tiếp tục từ mũi tẩy giun #3',
    birth: '2026-03-01',
    today: '2026-04-15',
    vaccine: 'cat_3in1_fvrcp',
    history: 'Tẩy giun: 22/03, 05/04',
    path: 'cat_kitten_history deworm',
    checks: ['Tẩy #3 due 19/04 target', 'FVRCP #1 sau tẩy #3'],
    input: {
      species: 'cat',
      birth: '2026-03-01',
      today: '2026-04-15',
      vaccine: 'cat_3in1_fvrcp',
      dewormings: [dewormDose('2026-03-22'), dewormDose('2026-04-05')],
    },
    expect: {
      lacks: [{ family: 'catDeworming', dose: 1 }, { family: 'catDeworming', dose: 2 }],
      has: [{ family: 'catDeworming', dose: 3, due: '2026-04-19' }],
    },
  },
  {
    id: 'CAT-H10',
    title: 'Mèo con tiêm và tẩy cùng ngày',
    group: 'Mèo — có lịch sử',
    fn: 'calculateCoreCareScheduleFromHistory',
    desc: 'Đảm bảo tẩy giun sau không lùi trước mũi trước',
    birth: '2026-04-01',
    today: '2026-07-11',
    vaccine: 'cat_3in1_fvrcp',
    history: 'FVRCP + tẩy: 10/07',
    path: 'buildCatKittenIntegratedSchedule history',
    checks: ['Tẩy giun tăng dần theo ngày'],
    input: {
      species: 'cat',
      birth: '2026-04-01',
      today: '2026-07-11',
      vaccine: 'cat_3in1_fvrcp',
      vaccines: [vaccineDose('cat_3in1_fvrcp', '2026-07-10')],
      dewormings: [dewormDose('2026-07-10')],
    },
    expect: {
      count: 7,
      sorted: true,
      has: [{ family: 'catDeworming', dose: 4, due: '2026-08-21' }],
    },
  },
  {
    id: 'CAT-H11',
    title: 'Mèo 9 tuần tiêm FVRCP hôm nay',
    group: 'Mèo — có lịch sử',
    fn: 'calculateCoreCareScheduleFromHistory',
    desc: 'Tiêm trước tẩy giun — tẩy defer 1 tuần',
    birth: '2025-12-12',
    today: '2026-02-14',
    vaccine: 'cat_3in1_fvrcp',
    history: 'FVRCP: 2026-02-14',
    path: 'cat_kitten_history + deworm defer',
    checks: ['FVRCP #2 +4 tuần', 'Tẩy giun defer sau vaccine'],
    input: {
      species: 'cat',
      birth: '2025-12-12',
      today: '2026-02-14',
      vaccine: 'cat_3in1_fvrcp',
      vaccines: [vaccineDose('cat_3in1_fvrcp', '2026-02-14')],
    },
    expect: {
      has: [{ family: 'catFvrcp', dose: 2, due: '2026-03-14' }],
      lacks: [{ family: 'catFvrcp', dose: 1 }],
    },
  },
  {
    id: 'CAT-H12',
    title: 'Mèo lớn >30 tuần tiêm FVRCP hôm nay',
    group: 'Mèo — có lịch sử',
    fn: 'calculateCoreCareScheduleFromHistory',
    desc: 'Case thực tế bé nhà Sen adopt chưa tẩy giun',
    birth: '2025-12-12',
    today: '2026-07-09',
    vaccine: 'cat_3in1_fvrcp',
    history: 'FVRCP: 2026-07-09',
    path: 'adult_catch_up + adjust',
    checks: ['Không lặp FVRCP #1', 'Tẩy giun +7 ngày'],
    input: {
      species: 'cat',
      birth: '2025-12-12',
      today: '2026-07-09',
      vaccine: 'cat_3in1_fvrcp',
      vaccines: [vaccineDose('cat_3in1_fvrcp', '2026-07-09')],
    },
    expect: {
      count: 3,
      dueDates: ['2026-07-09', '2026-07-16', '2026-08-06'],
      lacks: [{ family: 'catFvrcp', dose: 1 }],
    },
  },
  {
    id: 'CAT-H13',
    title: 'Mèo con 3 tẩy giun xong mới tiêm',
    group: 'Mèo — có lịch sử',
    fn: 'calculateCoreCareScheduleFromHistory',
    desc: 'Đúng guideline tẩy trước vaccine',
    birth: '2026-01-10',
    today: '2026-03-20',
    vaccine: 'cat_3in1_fvrcp',
    history: 'Tẩy: 31/01, 14/02, 28/02',
    path: 'cat_kitten_history',
    checks: ['FVRCP #1 = tẩy #3 + 7 ngày'],
    input: {
      species: 'cat',
      birth: '2026-01-10',
      today: '2026-03-20',
      vaccine: 'cat_3in1_fvrcp',
      dewormings: [dewormDose('2026-01-31'), dewormDose('2026-02-14'), dewormDose('2026-02-28')],
    },
    expect: {
      has: [{ family: 'catFvrcp', dose: 1, due: '2026-03-20', catchUp: true }],
      lacks: [{ family: 'catDeworming', dose: 3 }],
    },
  },
  {
    id: 'CAT-H14',
    title: 'Mèo 24 tuần đã tiêm FVRCP 4 tuần trước',
    group: 'Mèo — có lịch sử',
    fn: 'calculateCoreCareScheduleFromHistory',
    desc: 'Chuyển sang adult path, chờ mũi 2',
    birth: '2025-12-01',
    today: '2026-05-15',
    vaccine: 'cat_3in1_fvrcp',
    history: 'FVRCP: 2026-04-17',
    path: 'adult_catch_up',
    checks: ['FVRCP #2 due hôm nay (= mũi1 +28)'],
    input: {
      species: 'cat',
      birth: '2025-12-01',
      today: '2026-05-15',
      vaccine: 'cat_3in1_fvrcp',
      vaccines: [vaccineDose('cat_3in1_fvrcp', '2026-04-17')],
    },
    expect: {
      has: [{ family: 'catFvrcp', dose: 2, due: '2026-05-15' }],
      lacks: [{ family: 'catFvrcp', dose: 1 }],
    },
  },
  {
    id: 'CAT-H15',
    title: 'Mèo lịch sử 4-in-1',
    group: 'Mèo — có lịch sử',
    fn: 'calculateCoreCareScheduleFromHistory',
    desc: 'Tiêm Felocell 4-in-1 được map vào FVRCP',
    birth: '2026-02-01',
    today: '2026-04-01',
    vaccine: 'cat_4in1',
    history: '4-in-1: 2026-03-15',
    path: 'cat_kitten_history fvrcp',
    checks: ['FVRCP #2 due +4 tuần'],
    input: {
      species: 'cat',
      birth: '2026-02-01',
      today: '2026-04-01',
      vaccine: 'cat_4in1',
      vaccines: [vaccineDose('cat_4in1', '2026-03-15')],
    },
    expect: {
      lacks: [{ family: 'catFvrcp', dose: 1 }],
      has: [{ family: 'catFvrcp', dose: 2, due: '2026-04-12' }],
    },
  },
  {
    id: 'CAT-H16',
    title: 'Mèo lớn đã tiêm dại, chưa FVRCP',
    group: 'Mèo — có lịch sử',
    fn: 'calculateCoreCareScheduleFromHistory',
    desc: 'Chỉ còn FVRCP catch-up',
    birth: '2024-06-01',
    today: '2026-07-01',
    vaccine: 'cat_3in1_fvrcp',
    history: 'Rabies: 2026-06-01',
    path: 'adult_catch_up',
    checks: ['Ẩn dại', 'FVRCP #1 hôm nay'],
    input: {
      species: 'cat',
      birth: '2024-06-01',
      today: '2026-07-01',
      vaccine: 'cat_3in1_fvrcp',
      vaccines: [vaccineDose('cat_rabies', '2026-06-01')],
    },
    expect: {
      lacks: [{ family: 'catRabies', dose: 1 }],
      has: [{ family: 'catFvrcp', dose: 1, due: '2026-07-01' }],
    },
  },
  {
    id: 'CAT-H17',
    title: 'Mèo con tiêm FVRCP trong 7 ngày qua',
    group: 'Mèo — có lịch sử',
    fn: 'calculateCoreCareScheduleFromHistory',
    desc: 'Tẩy giun đầu tiên defer sau vaccine gần đây',
    birth: '2026-01-14',
    today: '2026-06-14',
    vaccine: 'cat_3in1_fvrcp',
    history: 'FVRCP: 2026-06-14',
    path: 'deferredDewormDueAfterRecentVaccine',
    checks: ['Tẩy giun đầu +7 ngày từ vaccine'],
    input: {
      species: 'cat',
      birth: '2026-01-14',
      today: '2026-06-14',
      vaccine: 'cat_3in1_fvrcp',
      vaccines: [vaccineDose('cat_3in1_fvrcp', '2026-06-14')],
    },
    expect: {
      has: [{ family: 'catDeworming', dose: 4, due: '2026-06-21' }],
    },
  },
  {
    id: 'CAT-H18',
    title: 'Mèo lớn tiêm hôm qua — thứ tự preview',
    group: 'Mèo — có lịch sử',
    fn: 'calculateCoreCareScheduleFromHistory',
    desc: '3 mũi sort: dại → tẩy → FVRCP #2',
    birth: '2025-01-01',
    today: '2026-07-11',
    vaccine: 'cat_3in1_fvrcp',
    history: 'FVRCP: 2026-07-10',
    path: 'finalizeScheduleRecommendations sort',
    checks: ['Thứ tự dueDate tăng dần'],
    input: {
      species: 'cat',
      birth: '2025-01-01',
      today: '2026-07-11',
      vaccine: 'cat_3in1_fvrcp',
      vaccines: [vaccineDose('cat_3in1_fvrcp', '2026-07-10')],
    },
    expect: { sorted: true, count: 3 },
  },
  {
    id: 'DOG-03',
    title: 'Chó chọn 7-in-1 có Lepto',
    group: 'Chó — lịch mới',
    fn: 'calculateCoreCareSchedule',
    desc: '7-in-1 gồm DHPP + Lepto, có spacing',
    birth: '2026-01-01',
    today: '2026-01-01',
    vaccine: 'dog_7in1',
    history: 'Không có',
    path: 'spaceInitialSchedule',
    checks: ['Có DHPP và Lepto', 'Tẩy giun #4 trước DHPP #1'],
    input: { species: 'dog', birth: '2026-01-01', today: '2026-01-01', vaccine: 'dog_7in1' },
    expect: {
      has: [
        { family: 'dogDhpp', dose: 1, due: '2026-02-26' },
        { family: 'dogLepto', dose: 1, due: '2026-03-26' },
      ],
      sorted: true,
    },
  },
  {
    id: 'DOG-04',
    title: 'Chó chọn 5-in-1 không có Lepto',
    group: 'Chó — lịch mới',
    fn: 'calculateCoreCareSchedule',
    desc: 'Sen chọn vaccine 5 bệnh — app vẫn map kèm Lepto trong combo',
    birth: '2026-01-01',
    today: '2026-01-01',
    vaccine: 'dog_5in1_dhppl',
    history: 'Không có',
    path: 'selectedInitialVaccineFamilies dog_5in1 + dog_7in1',
    checks: ['Có DHPP', 'Có Lepto (combo 5-in-1/7-in-1 trong app)'],
    input: { species: 'dog', birth: '2026-01-01', today: '2026-01-01', vaccine: 'dog_5in1_dhppl' },
    expect: {
      has: [
        { family: 'dogDhpp', dose: 1 },
        { family: 'dogLepto', dose: 1 },
      ],
    },
  },
  {
    id: 'DOG-05',
    title: 'Chó đúng 8 tuần tiêm DHPP lần 1',
    group: 'Chó — lịch mới',
    fn: 'calculateCoreCareSchedule',
    desc: 'Mốc WSAVA 8 tuần cho core vaccine',
    birth: '2026-05-22',
    today: '2026-07-17',
    vaccine: 'dog_5in1_dhppl',
    history: 'Không có',
    path: 'buildPrimarySeries',
    checks: ['DHPP #1 due hôm nay'],
    input: { species: 'dog', birth: '2026-05-22', today: '2026-07-17', vaccine: 'dog_5in1_dhppl' },
    expect: {
      has: [{ family: 'dogDhpp', dose: 1, due: '2026-07-17' }],
    },
  },
  {
    id: 'DOG-06',
    title: 'Chó 16 tuần catch-up',
    group: 'Chó — catch-up',
    fn: 'calculateCoreCareSchedule',
    desc: 'Bé adopt 16 tuần chưa tiêm',
    birth: '2026-03-20',
    today: '2026-07-12',
    vaccine: 'dog_5in1_dhppl',
    history: 'Không có',
    path: 'calculateDogSchedule catch-up',
    checks: ['DHPP #1 hôm nay', 'Dại 12 tuần tuổi đã qua'],
    input: { species: 'dog', birth: '2026-03-20', today: '2026-07-12', vaccine: 'dog_5in1_dhppl' },
    expect: {
      has: [
        { family: 'dogDhpp', dose: 1, due: '2026-07-19', catchUp: true },
        { family: 'dogRabies', dose: 1, due: '2026-08-16', catchUp: true },
      ],
    },
  },
  {
    id: 'DOG-07',
    title: 'Chó trưởng thành 7-in-1',
    group: 'Chó — người lớn',
    fn: 'calculateCoreCareSchedule',
    desc: 'Chó >26 tuần adopt mới',
    birth: '2024-01-01',
    today: '2026-07-01',
    vaccine: 'dog_7in1',
    history: 'Không có',
    path: 'adultDogCatchUp',
    checks: ['DHPP + Lepto due hôm nay', 'Mũi 2 +28 ngày'],
    input: { species: 'dog', birth: '2024-01-01', today: '2026-07-01', vaccine: 'dog_7in1' },
    expect: {
      has: [
        { family: 'dogDhpp', dose: 1, due: '2026-07-01' },
        { family: 'dogLepto', dose: 1, due: '2026-07-01' },
        { family: 'dogDhpp', dose: 2, due: '2026-07-29' },
      ],
    },
  },
  {
    id: 'DOG-08',
    title: 'Chó 12 tuần dại đúng mốc',
    group: 'Chó — lịch mới',
    fn: 'calculateCoreCareSchedule',
    desc: 'Rabies target 12 tuần tuổi',
    birth: '2026-04-15',
    today: '2026-07-08',
    vaccine: 'dog_5in1_dhppl',
    history: 'Không có',
    path: 'buildSingleRecommendation rabies',
    checks: ['Dại due hôm nay'],
    input: { species: 'dog', birth: '2026-04-15', today: '2026-07-08', vaccine: 'dog_5in1_dhppl' },
    expect: {
      has: [{ family: 'dogRabies', dose: 1, due: '2026-08-12', catchUp: true }],
    },
  },
  {
    id: 'DOG-09',
    title: 'Lịch chó con sắp xếp theo ngày',
    group: 'Chó — lịch mới',
    fn: 'calculateCoreCareSchedule',
    desc: 'dueDate tăng dần toàn bộ lịch',
    birth: '2026-01-01',
    today: '2026-01-01',
    vaccine: 'dog_7in1',
    history: 'Không có',
    path: 'finalizeScheduleRecommendations',
    checks: ['Sorted ascending'],
    input: { species: 'dog', birth: '2026-01-01', today: '2026-01-01', vaccine: 'dog_7in1' },
    expect: { sorted: true, count: 14 },
  },
  {
    id: 'DOG-10',
    title: 'Chó tẩy giun trước vaccine core',
    group: 'Chó — lịch mới',
    fn: 'calculateCoreCareSchedule',
    desc: 'Tẩy giun #4 cùng tuần DHPP #1',
    birth: '2026-01-01',
    today: '2026-01-01',
    vaccine: 'dog_5in1_dhppl',
    history: 'Không có',
    path: 'buildDewormingSeries',
    checks: ['Tẩy #4 due 26/02 trước DHPP #1'],
    input: { species: 'dog', birth: '2026-01-01', today: '2026-01-01', vaccine: 'dog_5in1_dhppl' },
    expect: {
      has: [
        { family: 'dogDeworming', dose: 4, due: '2026-02-19' },
        { family: 'dogDhpp', dose: 1, due: '2026-02-26' },
      ],
    },
  },
  {
    id: 'DOG-H01',
    title: 'Chó con đã tiêm DHPP mũi 1',
    group: 'Chó — có lịch sử',
    fn: 'calculateCoreCareScheduleFromHistory',
    desc: 'Tiếp tục mũi 2 từ ngày tiêm thực tế',
    birth: '2026-01-01',
    today: '2026-03-01',
    vaccine: 'dog_5in1_dhppl',
    history: '5-in-1: 2026-02-15',
    path: 'dog_history_fallback',
    checks: ['Ẩn DHPP #1', 'DHPP #2 due 15/03'],
    input: {
      species: 'dog',
      birth: '2026-01-01',
      today: '2026-03-01',
      vaccine: 'dog_5in1_dhppl',
      vaccines: [vaccineDose('dog_5in1_dhppl', '2026-02-15')],
    },
    expect: {
      lacks: [{ family: 'dogDhpp', dose: 1 }],
      has: [{ family: 'dogDhpp', dose: 2, due: '2026-03-15' }],
    },
  },
  {
    id: 'DOG-H02',
    title: 'Chó lớn tiêm 5-in-1 hôm nay',
    group: 'Chó — có lịch sử',
    fn: 'calculateCoreCareScheduleFromHistory',
    desc: 'Adult catch-up + defer tẩy giun',
    birth: '2025-01-01',
    today: '2026-07-11',
    vaccine: 'dog_5in1_dhppl',
    history: '5-in-1: 2026-07-11',
    path: 'adjustDogDewormingForRecentVaccination',
    checks: ['DHPP #2 +4 tuần', 'Tẩy giun +7 ngày'],
    input: {
      species: 'dog',
      birth: '2025-01-01',
      today: '2026-07-11',
      vaccine: 'dog_5in1_dhppl',
      vaccines: [vaccineDose('dog_5in1_dhppl', '2026-07-11')],
    },
    expect: {
      lacks: [{ family: 'dogDhpp', dose: 1 }],
      has: [
        { family: 'dogDhpp', dose: 2, due: '2026-08-08' },
        { family: 'dogDeworming', dose: 1, due: '2026-07-18' },
      ],
    },
  },
  {
    id: 'DOG-H03',
    title: 'Chó con đã tiêm 2 mũi DHPP',
    group: 'Chó — có lịch sử',
    fn: 'calculateCoreCareScheduleFromHistory',
    desc: 'Chờ mũi 3 và dại',
    birth: '2026-01-01',
    today: '2026-04-01',
    vaccine: 'dog_5in1_dhppl',
    history: '5-in-1: 26/02, 26/03',
    path: 'adjustDogScheduleForAdministeredVaccines',
    checks: ['DHPP #3 due 12/04'],
    input: {
      species: 'dog',
      birth: '2026-01-01',
      today: '2026-04-01',
      vaccine: 'dog_5in1_dhppl',
      vaccines: [vaccineDose('dog_5in1_dhppl', '2026-02-26'), vaccineDose('dog_5in1_dhppl', '2026-03-26')],
    },
    expect: {
      lacks: [{ family: 'dogDhpp', dose: 1 }, { family: 'dogDhpp', dose: 2 }],
      has: [{ family: 'dogDhpp', dose: 3, due: '2026-04-23' }],
    },
  },
  {
    id: 'DOG-H04',
    title: 'Chó tiêm trong 7 ngày defer tẩy giun',
    group: 'Chó — có lịch sử',
    fn: 'calculateCoreCareScheduleFromHistory',
    desc: 'Cùng rule PRE_VACCINE_DEWORMING_DAYS cho chó',
    birth: '2025-06-01',
    today: '2026-07-05',
    vaccine: 'dog_5in1_dhppl',
    history: '5-in-1: 2026-07-01',
    path: 'adjustDogDewormingForRecentVaccination',
    checks: ['Tẩy giun sau vaccine 4 ngày trước'],
    input: {
      species: 'dog',
      birth: '2025-06-01',
      today: '2026-07-05',
      vaccine: 'dog_5in1_dhppl',
      vaccines: [vaccineDose('dog_5in1_dhppl', '2026-07-01')],
    },
    expect: {
      has: [{ family: 'dogDeworming', dose: 1, due: '2026-07-08' }],
    },
  },
  {
    id: 'DOG-H05',
    title: 'Chó lớn tiêm 7-in-1 hôm nay',
    group: 'Chó — có lịch sử',
    fn: 'calculateCoreCareScheduleFromHistory',
    desc: '7-in-1 map cả DHPP và Lepto',
    birth: '2024-03-01',
    today: '2026-07-10',
    vaccine: 'dog_7in1',
    history: '7-in-1: 2026-07-10',
    path: 'adultDogCatchUp + adjust',
    checks: ['Ẩn DHPP #1 và Lepto #1', 'Mũi 2 +28 ngày'],
    input: {
      species: 'dog',
      birth: '2024-03-01',
      today: '2026-07-10',
      vaccine: 'dog_7in1',
      vaccines: [vaccineDose('dog_7in1', '2026-07-10')],
    },
    expect: {
      lacks: [{ family: 'dogDhpp', dose: 1 }, { family: 'dogLepto', dose: 1 }],
      has: [{ family: 'dogDhpp', dose: 2, due: '2026-08-07' }],
    },
  },
  {
    id: 'DOG-H06',
    title: 'Chó con tiêm Lepto sau DHPP',
    group: 'Chó — có lịch sử',
    fn: 'calculateCoreCareScheduleFromHistory',
    desc: 'Spacing giữa các họ vaccine',
    birth: '2026-01-01',
    today: '2026-04-01',
    vaccine: 'dog_7in1',
    history: '7-in-1: 26/02, 26/03',
    path: 'dog_history_fallback',
    checks: ['Lepto #2 theo spacing'],
    input: {
      species: 'dog',
      birth: '2026-01-01',
      today: '2026-04-01',
      vaccine: 'dog_7in1',
      vaccines: [vaccineDose('dog_7in1', '2026-02-26'), vaccineDose('dog_7in1', '2026-03-26')],
    },
    expect: {
      has: [{ family: 'dogDhpp', dose: 3, due: '2026-04-23' }],
    },
  },
  {
    id: 'DOG-H07',
    title: 'Chó con đã tẩy giun 1 lần',
    group: 'Chó — có lịch sử',
    fn: 'calculateCoreCareScheduleFromHistory',
    desc: 'Tiếp tục chuỗi tẩy giun puppy',
    birth: '2026-02-01',
    today: '2026-03-01',
    vaccine: 'dog_5in1_dhppl',
    history: 'Tẩy giun: 2026-02-15',
    path: 'dog deworm series',
    checks: ['Tẩy #2 due 29/02 hoặc catch-up'],
    input: {
      species: 'dog',
      birth: '2026-02-01',
      today: '2026-03-01',
      vaccine: 'dog_5in1_dhppl',
      dewormings: [dewormDose('2026-02-15')],
    },
    expect: {
      has: [{ family: 'dogDeworming', dose: 2, due: '2026-03-15' }],
      minCount: 10,
    },
  },
  {
    id: 'DOG-H08',
    title: 'Chó trùng mũi tiêm trong lịch sử',
    group: 'Chó — có lịch sử',
    fn: 'calculateCoreCareScheduleFromHistory',
    desc: 'Dedupe không bỏ sót mũi kế tiếp',
    birth: '2025-01-01',
    today: '2026-07-11',
    vaccine: 'dog_5in1_dhppl',
    history: '5-in-1 duplicate 11/07',
    path: 'dedupeAdministeredVaccineDoses',
    checks: ['Vẫn có DHPP #2'],
    input: {
      species: 'dog',
      birth: '2025-01-01',
      today: '2026-07-11',
      vaccine: 'dog_5in1_dhppl',
      vaccines: [vaccineDose('dog_5in1_dhppl', '2026-07-11'), vaccineDose('dog_5in1_dhppl', '2026-07-11')],
    },
    expect: {
      has: [{ family: 'dogDhpp', dose: 2, due: '2026-08-08' }],
      lacks: [{ family: 'dogDhpp', dose: 1 }],
    },
  },
  {
    id: 'NEXT-04',
    title: 'Chó trưởng thành booster sau primary',
    group: 'Mũi tiêm kế tiếp',
    fn: 'calculateNextVaccinationSchedule',
    desc: 'Đã xong 3 mũi DHPP → booster 1 năm',
    birth: '—',
    today: '2026-06-12',
    vaccine: '—',
    history: '3 mũi 5-in-1 năm trước',
    path: 'booster ONE_YEAR_DAYS',
    checks: ['1 mũi booster due'],
    input: {
      species: 'dog',
      today: '2026-06-12',
      petAgeMonths: 14,
      vaccines: [
        vaccineDose('dog_5in1_dhppl', '2025-06-12'),
        vaccineDose('dog_5in1_dhppl', '2025-07-10'),
        vaccineDose('dog_5in1_dhppl', '2025-08-07'),
      ],
    },
    expect: {
      count: 1,
      has: [{ vaccineId: 'dog_5in1_dhppl', dose: 4, due: '2026-08-07' }],
    },
  },
  {
    id: 'NEXT-05',
    title: 'Mèo trẻ FVRCP mũi 2',
    group: 'Mũi tiêm kế tiếp',
    fn: 'calculateNextVaccinationSchedule',
    desc: 'Sau mũi 1 đúng 4 tuần',
    birth: '—',
    today: '2026-06-12',
    vaccine: '—',
    history: 'FVRCP: 2026-05-15, 4 tháng tuổi',
    path: 'primary series cat fvrcp',
    checks: ['Mũi 2 due 12/06', 'Mũi 3 due 10/07'],
    input: {
      species: 'cat',
      today: '2026-06-12',
      petAgeMonths: 4,
      vaccines: [vaccineDose('cat_3in1_fvrcp', '2026-05-15')],
    },
    expect: {
      count: 2,
      has: [
        { vaccineId: 'cat_3in1_fvrcp', dose: 2, due: '2026-06-12' },
        { vaccineId: 'cat_3in1_fvrcp', dose: 3, due: '2026-07-10' },
      ],
    },
  },
  {
    id: 'NEXT-06',
    title: 'Chó 7-in-1 mũi kế tiếp',
    group: 'Mũi tiêm kế tiếp',
    fn: 'calculateNextVaccinationSchedule',
    desc: '7-in-1 đếm cho primary DHPP',
    birth: '—',
    today: '2026-06-12',
    vaccine: '—',
    history: '7-in-1: 2026-06-12, 3 tháng',
    path: 'vaccineSeriesForDose dog_7in1',
    checks: ['Còn mũi 2 và 3'],
    input: {
      species: 'dog',
      today: '2026-06-12',
      petAgeMonths: 3,
      vaccines: [vaccineDose('dog_7in1', '2026-06-12')],
    },
    expect: {
      count: 2,
      has: [{ vaccineId: 'dog_7in1', dose: 2, due: '2026-07-10' }],
    },
  },
  {
    id: 'NEXT-07',
    title: 'Bỏ qua mũi tiêm ngày tương lai',
    group: 'Mũi tiêm kế tiếp',
    fn: 'calculateNextVaccinationSchedule',
    desc: 'Chỉ tính mũi đã tiêm đến hôm nay',
    birth: '—',
    today: '2026-06-12',
    vaccine: '—',
    history: 'Mũi future + past',
    path: 'administeredAt <= today filter',
    checks: ['Future dose không tính'],
    input: {
      species: 'cat',
      today: '2026-06-12',
      petAgeMonths: 6,
      vaccines: [
        vaccineDose('cat_3in1_fvrcp', '2026-06-01'),
        vaccineDose('cat_3in1_fvrcp', '2026-06-20'),
      ],
    },
    expect: {
      has: [{ vaccineId: 'cat_3in1_fvrcp', dose: 2, due: '2026-06-29' }],
    },
  },
  {
    id: 'NEXT-08',
    title: 'Mèo FeLV primary series',
    group: 'Mũi tiêm kế tiếp',
    fn: 'calculateNextVaccinationSchedule',
    desc: 'FeLV 2 mũi cho mèo trẻ',
    birth: '—',
    today: '2026-06-01',
    vaccine: '—',
    history: 'FeLV: 2026-05-04, 3 tháng',
    path: 'vaccineSeriesForDose cat_felv',
    checks: ['Mũi 2 due 01/06'],
    input: {
      species: 'cat',
      today: '2026-06-01',
      petAgeMonths: 3,
      vaccines: [vaccineDose('cat_felv', '2026-05-04')],
    },
    expect: {
      count: 1,
      has: [{ vaccineId: 'cat_felv', dose: 2, due: '2026-06-01' }],
    },
  },
  {
    id: 'NEXT-09',
    title: 'Chó dại booster hàng năm',
    group: 'Mũi tiêm kế tiếp',
    fn: 'calculateNextVaccinationSchedule',
    desc: 'Sau mũi dại đầu',
    birth: '—',
    today: '2026-03-15',
    vaccine: '—',
    history: 'Rabies: 2025-03-15',
    path: 'booster rabies',
    checks: ['Booster due 2026-03-15'],
    input: {
      species: 'dog',
      today: '2026-03-15',
      petAgeMonths: 18,
      vaccines: [vaccineDose('dog_rabies', '2025-03-15')],
    },
    expect: {
      count: 1,
      has: [{ vaccineId: 'dog_rabies', dose: 2, due: '2026-03-15' }],
    },
  },
  {
    id: 'NEXT-10',
    title: 'Chó trẻ đủ 2 mũi DHPP',
    group: 'Mũi tiêm kế tiếp',
    fn: 'calculateNextVaccinationSchedule',
    desc: 'Còn mũi 3 primary',
    birth: '—',
    today: '2026-06-12',
    vaccine: '—',
    history: '2 mũi 5-in-1',
    path: 'primary dose 3',
    checks: ['Chỉ còn mũi 3'],
    input: {
      species: 'dog',
      today: '2026-06-12',
      petAgeMonths: 4,
      vaccines: [vaccineDose('dog_5in1_dhppl', '2026-05-01'), vaccineDose('dog_5in1_dhppl', '2026-06-12')],
    },
    expect: {
      count: 1,
      has: [{ vaccineId: 'dog_5in1_dhppl', dose: 3, due: '2026-07-10' }],
    },
  },
  {
    id: 'NEXT-11',
    title: 'Mèo mũi 2 chưa quá 42 ngày',
    group: 'Mũi tiêm kế tiếp',
    fn: 'calculateNextVaccinationSchedule',
    desc: 'Không restart khi còn trong cửa sổ 6 tuần',
    birth: '—',
    today: '2026-05-20',
    vaccine: '—',
    history: '4-in-1: 2026-04-15, 4 tháng',
    path: 'LAPSED_PRIMARY_SERIES_DAYS boundary',
    checks: ['isRestartRequired = false'],
    input: {
      species: 'cat',
      today: '2026-05-20',
      petAgeMonths: 4,
      vaccines: [vaccineDose('cat_4in1', '2026-04-15')],
    },
    expect: {
      has: [{ vaccineId: 'cat_4in1', dose: 2, due: '2026-05-20' }],
    },
  },
  {
    id: 'NEXT-12',
    title: 'Horizon 6 tháng giới hạn mũi',
    group: 'Mũi tiêm kế tiếp',
    fn: 'calculateNextVaccinationSchedule',
    desc: 'Chỉ 1 mũi trong horizon 6 tháng khi mới tiêm gần đây',
    birth: '—',
    today: '2026-01-01',
    vaccine: '—',
    history: 'FVRCP: 2025-12-01, trưởng thành',
    path: 'horizonMonths + young primary',
    checks: ['Mũi 2 due hôm nay (catch-up)'],
    input: {
      species: 'cat',
      today: '2026-01-01',
      petAgeMonths: 14,
      horizonMonths: 6,
      vaccines: [vaccineDose('cat_3in1_fvrcp', '2025-12-01')],
    },
    expect: {
      count: 1,
      has: [{ vaccineId: 'cat_3in1_fvrcp', dose: 2, due: '2026-01-01', catchUp: true }],
    },
  },
  {
    id: 'EDGE-02',
    title: 'Ngày sinh sau hôm nay',
    group: 'Biên / lỗi',
    fn: 'calculateCoreCareScheduleFromHistory',
    desc: 'Birth date in future → không tạo lịch',
    birth: '2027-01-01',
    today: '2026-07-01',
    vaccine: 'cat_3in1_fvrcp',
    history: 'Không có',
    path: 'birth_before_today guard',
    checks: ['Kết quả rỗng'],
    input: {
      species: 'cat',
      birth: '2027-01-01',
      today: '2026-07-01',
      vaccine: 'cat_3in1_fvrcp',
    },
    expect: { count: 0 },
  },
  {
    id: 'EDGE-03',
    title: 'Species rỗng',
    group: 'Biên / lỗi',
    fn: 'calculateCoreCareSchedule',
    desc: 'Chuỗi species trống',
    birth: '2026-01-01',
    today: '2026-01-01',
    vaccine: '—',
    history: 'species=""',
    path: 'normalizeCoreCareScheduleSpecies',
    checks: ['[]'],
    input: { species: '', birth: '2026-01-01', today: '2026-01-01' },
    expect: { count: 0 },
  },
  {
    id: 'EDGE-04',
    title: 'Lịch sử chỉ tẩy giun mèo con',
    group: 'Biên / lỗi',
    fn: 'calculateCoreCareScheduleFromHistory',
    desc: 'Không vaccine, 1 lần tẩy giun',
    birth: '2026-05-01',
    today: '2026-06-15',
    vaccine: 'cat_3in1_fvrcp',
    history: 'Tẩy: 2026-06-01',
    path: 'cat_kitten_history deworm only',
    checks: ['Tiếp tục tẩy #2'],
    input: {
      species: 'cat',
      birth: '2026-05-01',
      today: '2026-06-15',
      vaccine: 'cat_3in1_fvrcp',
      dewormings: [dewormDose('2026-06-01')],
    },
    expect: {
      lacks: [{ family: 'catDeworming', dose: 1 }],
      has: [{ family: 'catDeworming', dose: 2 }],
    },
  },
  {
    id: 'EDGE-05',
    title: 'Cat history không vaccine id hợp lệ',
    group: 'Biên / lỗi',
    fn: 'calculateCoreCareScheduleFromHistory',
    desc: 'Chỉ có tẩy giun, vaccine list rỗng',
    birth: '2025-01-01',
    today: '2026-07-01',
    vaccine: 'cat_3in1_fvrcp',
    history: 'Không vaccine',
    path: 'adult_catch_up empty vaccines',
    checks: ['Full adult catch-up'],
    input: {
      species: 'cat',
      birth: '2025-01-01',
      today: '2026-07-01',
      vaccine: 'cat_3in1_fvrcp',
    },
    expect: {
      has: [
        { family: 'catFvrcp', dose: 1, due: '2026-07-01' },
        { family: 'catDeworming', dose: 1, due: '2026-07-01' },
      ],
    },
  },
  {
    id: 'NORM-01',
    title: 'Nhận diện Purevax tiếng Việt',
    group: 'Chuẩn hóa tên vaccine',
    fn: 'normalizeManualVaccineId',
    desc: 'Ghi tay "Purevax 3 trong 1"',
    birth: '—',
    today: '2026-07-01',
    vaccine: '—',
    history: 'text=Purevax 3 trong 1',
    path: 'normalizeManualVaccineId cat',
    checks: ['→ cat_3in1_fvrcp'],
    input: { species: 'cat', today: '2026-07-01', normalizeText: 'Purevax 3 trong 1', normalizeSpecies: 'cat' },
    expect: { normalizeId: 'cat_3in1_fvrcp' },
  },
  {
    id: 'NORM-02',
    title: 'Nhận diện Rabisin',
    group: 'Chuẩn hóa tên vaccine',
    fn: 'normalizeManualVaccineId',
    desc: 'Vaccine dại chó',
    birth: '—',
    today: '2026-07-01',
    vaccine: '—',
    history: 'text=Rabisin',
    path: 'normalizeManualVaccineId dog rabies',
    checks: ['→ dog_rabies'],
    input: { species: 'dog', today: '2026-07-01', normalizeText: 'Rabisin cho chó', normalizeSpecies: 'dog' },
    expect: { normalizeId: 'dog_rabies' },
  },
  {
    id: 'NORM-03',
    title: 'Nhận diện FeLV',
    group: 'Chuẩn hóa tên vaccine',
    fn: 'normalizeManualVaccineId',
    desc: 'Bạch cầu mèo',
    birth: '—',
    today: '2026-07-01',
    vaccine: '—',
    history: 'text=vaccine bạch cầu',
    path: 'normalizeManualVaccineId cat felv',
    checks: ['→ cat_felv'],
    input: { species: 'cat', today: '2026-07-01', normalizeText: 'vaccine bạch cầu', normalizeSpecies: 'cat' },
    expect: { normalizeId: 'cat_felv' },
  },
  {
    id: 'NORM-04',
    title: 'Nhận diện 7-in-1 chó',
    group: 'Chuẩn hóa tên vaccine',
    fn: 'normalizeManualVaccineId',
    desc: 'Vaccine 7 bệnh có Lepto',
    birth: '—',
    today: '2026-07-01',
    vaccine: '—',
    history: 'text=7 trong 1',
    path: 'normalizeManualVaccineId dog 7in1',
    checks: ['→ dog_7in1'],
    input: { species: 'dog', today: '2026-07-01', normalizeText: 'Vaccine 7 trong 1 có lepto', normalizeSpecies: 'dog' },
    expect: { normalizeId: 'dog_7in1' },
  },
  {
    id: 'NORM-05',
    title: 'Text không nhận diện được',
    group: 'Chuẩn hóa tên vaccine',
    fn: 'normalizeManualVaccineId',
    desc: 'Ghi chú tự do không match',
    birth: '—',
    today: '2026-07-01',
    vaccine: '—',
    history: 'text=không rõ',
    path: 'normalizeManualVaccineId null',
    checks: ['→ null'],
    input: { species: 'cat', today: '2026-07-01', normalizeText: 'thuốc đặc biệt xyz', normalizeSpecies: 'cat' },
    expect: { normalizeId: null },
  },
];

export function extendedCaseForHtml(testCase: ScheduleTestCaseDef) {
  return {
    id: testCase.id,
    fn: testCase.fn,
    group: testCase.group,
    desc: testCase.desc,
    birth: testCase.birth,
    today: testCase.today,
    vaccine: testCase.vaccine,
    history: testCase.history,
    path: testCase.path,
    checks: testCase.checks,
    review: testCase.review,
    run: () => runScheduleTestCase(testCase),
  };
}
